package co.unicauca.restaurant.client.presentation;

import co.unicauca.restaurant.client.access.Factory;
import co.unicauca.restaurant.commons.domain.User;
import co.unicauca.restaurant.client.domain.services.UserService;
import static co.unicauca.restaurant.client.infra.Messages.successMessage;
import co.unicauca.restaurant.client.access.IUserAccess;
import co.unicauca.restaurant.client.domain.services.PlateService;
import co.unicauca.restaurant.commons.domain.Plate;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Interfaz gráfica de Consultar clientes
 *
 * @author Libardo Pantoja
 *
 */
public class GUIPlate extends javax.swing.JInternalFrame {

    PlateService  servicioPlato;
    /**
     * Constructor
     */
    
    
    public GUIPlate(PlateService  servicioPlato) {
       
        
        initComponents();
        
        setSize(870, 500);
        this.servicioPlato=servicioPlato;
        //btnAgregar.setVisible(false);
        

    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCentro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CBType = new javax.swing.JComboBox<>();
        pnlSur = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        pnlNorte = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Plato");

        pnlCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlCentro.setMaximumSize(new java.awt.Dimension(32767, 50000));
        pnlCentro.setLayout(new java.awt.GridLayout(5, 2, 0, 2));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre Componente");
        pnlCentro.add(jLabel1);
        pnlCentro.add(txtName);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Precio Componente");
        pnlCentro.add(jLabel2);

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        pnlCentro.add(txtPrice);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Descripcion Componente");
        pnlCentro.add(jLabel3);

        txtDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescriptionActionPerformed(evt);
            }
        });
        pnlCentro.add(txtDescription);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Tipo Componente");
        pnlCentro.add(jLabel5);

        CBType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Principio", "Proteina ", "Bebida" }));
        pnlCentro.add(CBType);

        getContentPane().add(pnlCentro, java.awt.BorderLayout.CENTER);

        pnlSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnlSur.add(btnAgregar);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlSur.add(btnCerrar);

        getContentPane().add(pnlSur, java.awt.BorderLayout.SOUTH);

        pnlNorte.setBorder(new javax.swing.border.MatteBorder(null));
        pnlNorte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Crear Componente");
        pnlNorte.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        getContentPane().add(pnlNorte, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed
    // public String getTxtyId() {
    // return txtId.getText();
    //}

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if (txtName.getText() != null && txtDescription.getText() != null  && txtPrice.getText() != null) {
            Plate plato = new Plate( txtName.getText(), txtPrice.getText(), txtDescription.getText(),CBType.getSelectedItem().toString());
            try {
                String res = servicioPlato.createPlate(plato);
                if (!res.equals("FALLO")) {
                    JOptionPane.showMessageDialog(null, "plato agregado con exito");
                    txtName.setText("");
                    txtPrice.setText("");
                    txtDescription.setText("");
                    
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "El plato ya esta registrado" + ex.getMessage());

            }
        }

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescriptionActionPerformed

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed
    /**
     * Muestra los datos en el formulario
     *
     * @param customer cliente
     */
    private void showData(User customer) {
//        txtFirstName.setText(customer.getFirstName());
//        txtLastName.setText(customer.getLastName());
//        txtAddress.setText(customer.getAddress());
//        txtMobile.setText(customer.getMobile());
//        txtEmail.setText(customer.getEmail());
//        txtGender.setText(customer.getGender());
    }

    public void clearControls() {
        //txtFirstName.setText("");
        txtName.setText("");
        //     txtAddress.setText("");
        //   txtMobile.setText("");
        // txtEmail.setText("");
        // txtGender.setText("");
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBType;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel pnlCentro;
    private javax.swing.JPanel pnlNorte;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables

    
}
